user_agent = "curl/7.83. 1"

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [ 
    '.*mathstatbites\.org.*',
    '.*wrps\.org.*',
    '.*pubs\.acs\.org.*',
    '.*linkedin\.com.*',
    '.*nrl.navy.mil.*'
 ]

exclude_path = ["themes"]

include_mail = true
