name: Links

on:
  workflow_run:
    workflows: ["Zola on GitHub Pages"]
    types: [completed] #requested
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@ef8c8f32c278e9eed290c6e6c96748f16b6cd335 # for v1.8.0
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: link-checker-issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2.3.0
        with:
          state: open
          labels: link-checker, automated issue

      - name: Create Issue From File
        if: ${{ env.lychee_exit_code != 0 && steps.last-issue.outputs.has-found == 'false' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          token: ${{secrets.GITHUB_TOKEN}}
          labels: link-checker, automated issue

      - name: Comment on Found Issue
        if: ${{ env.lychee_exit_code != 0 && steps.last-issue.outputs.has-found == 'true' }}
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          body-path: ./lychee/out.md
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          token: ${{secrets.GITHUB_TOKEN}}
