name: Links

on:
  workflow_run:
    workflows: ["Zola on GitHub Pages"]
    types: [completed] #requested
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@2ac9f030ccdea0033e2510a23a67da2a2da98492 # for v1.8.0
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: link-checker-issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2.1.0
        with:
          state: open
          labels: link-checker, automated issue

      - name: Create Issue From File Found Past
        if: ${{ steps.last-issue.outputs.has-found == 'true' }} #env.lychee_exit_code != 0 &&
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: "${{ steps.last-issue.outputs.issue_number }}"
          token: ${{secrets.GITHUB_TOKEN}}
          labels: link-checker, automated issue

      - name: Create Issue From File No Past
        if: ${{ steps.last-issue.outputs.has-found == 'false' }} #env.lychee_exit_code != 0 &&
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          token: ${{secrets.GITHUB_TOKEN}}
          labels: link-checker, automated issue
