name: Links

on:
  workflow_run:
    workflows: ["Zola on GitHub Pages"]
    types: [completed] #requested
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@5a5fc0bef7bcf1858217e7c9a8d4c01ec79dbeaf # for v1.8.0
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: link-checker-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link-checker

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee/out.md
          token: ${{secrets.GITHUB_TOKEN}}
          labels: |
            link-checker